### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by sdwilsh** [sdwilsh/siobrultech-protocols#84]
I lost power last night, and when my docker container came back up, I'm now constantly getting this:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py", line 7, in <module>
    asyncio.get_event_loop().run_until_complete(bs2m.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 50, in start
    await self._setup_gem(device_connection)
  File "/src/brultech_serial2mqtt/brultech_serial2mqtt/__init__.py", line 115, in _setup_gem
    await connection.synchronize_time()
  File "/usr/local/lib/python3.10/dist-packages/aiobrultech_serial/__init__.py", line 117, in synchronize_time
    success = await api.synchronize_time(self._protocol)
  File "/usr/local/lib/python3.10/dist-packages/siobrultech_protocols/gem/api.py", line 168, in synchronize_time
    return await set_date_and_time(protocol, time, serial_number)
  File "/usr/local/lib/python3.10/dist-packages/siobrultech_protocols/gem/api.py", line 127, in set_date_and_time
    async with call_api(SET_DATE_AND_TIME, protocol, serial_number) as f:
  File "/usr/lib/python3.10/contextlib.py", line 217, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/siobrultech_protocols/gem/api.py", line 90, in call_api
    protocol.end_api_request()
  File "/usr/local/lib/python3.10/dist-packages/siobrultech_protocols/gem/protocol.py", line 307, in end_api_request
    self._expect_state(
  File "/usr/local/lib/python3.10/dist-packages/siobrultech_protocols/gem/protocol.py", line 327, in _expect_state
    raise ProtocolStateException(actual=self._state, expected=expected_state)
siobrultech_protocols.gem.protocol.ProtocolStateException: Expected state to be SENT_PACKET_DELAY_REQUEST, or RECEIVED_API_RESPONSE; but got SENT_API_REQUEST!
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
/src/brultech_serial2mqtt/brultech_serial2mqtt/__main__.py:7: DeprecationWarning: There is no current event loop
  asyncio.get_event_loop().run_until_complete(bs2m.start())
```

I suspect the issue is in this library being too strict, so filing the tracking issue here.

**Comment by sdwilsh** [comment]
I enabled some logging, and this is what we get from our `DEBUG` logs:
```
2022-10-30 13:50:37,570 - brultech_serial2mqtt - INFO - Setting up GEM device...
2022-10-30 13:50:37,575 - siobrultech_protocols.gem.protocol - INFO - 281473438083168: Connection opened
2022-10-30 13:50:37,576 - siobrultech_protocols.gem.protocol - DEBUG - 281473438083168: Starting API request. Requesting packet delay...
'...-10-30 13:50:40,581 - siobrultech_protocols.gem.protocol - DEBUG - 281473438083168: Sending API request '^^^SYSDTM22,10,30,13,50,40
2022-10-30 13:50:40,593 - siobrultech_protocols.gem.protocol - DEBUG - 281473438083168: Received 8 bytes
2022-10-30 13:50:43,587 - siobrultech_protocols.gem.protocol - INFO - 281473438083168: Connection closed
```

**Comment by sdwilsh** [comment]
The docs for the PDL command doesn't say it stops sending a packet if it was in-process of sending a packet, which is fun.  Therefore, we should be waiting for a packet to complete before attempting to send a command.  How I've never hit an issue with this...I do not know.

**Comment by sdwilsh** [comment]
So after all that effort today, changing the time worked (in that the feature I added worked), but it didn't fix the issue.  Out of desperation, I restarted the GEM, and...it works now with the original default.  I'll leave this code in because I think it's useful, but oy.
